# Generated by Django 4.0.3 on 2022-03-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('category', models.CharField(choices=[('------------', '------------'), ('Sport', 'Sport'), ('Politics', 'Politics'), ('Crypto', 'Crypto'), ('Gaming', 'Gaming'), ('Movies', 'Movies'), ('Other', 'Other')], max_length=100)),
            ],
        ),
    ]
