# Generated by Django 4.0.3 on 2022-03-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusername',
            name='age',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
