# Generated by Django 4.0.3 on 2022-03-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_appusername_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appusername',
            name='age',
        ),
    ]
