# Generated by Django 4.0.3 on 2022-03-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_appusername_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Politics', 'Politics'), ('Article', 'Article'), ('Fun Fact', 'Fun Fact'), ('Joke', 'Joke'), ('Crypto', 'Crypto'), ('Gaming', 'Gaming'), ('Movies', 'Movies'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
