# Generated by Django 4.0.3 on 2022-03-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_remove_post_user_post_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='usera',
        ),
    ]
