# Generated by Django 4.0.3 on 2022-03-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(),
        ),
    ]
