# Generated by Django 4.0.3 on 2022-03-09 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.user'),
            preserve_default=False,
        ),
    ]
