# Generated by Django 4.0.3 on 2022-04-07 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_images_title_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusername',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
