# Generated by Django 4.0.3 on 2022-03-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_alter_post_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='to_user',
        ),
    ]
